---
dependencies:
  - { role: docker-server-linode }
  - { role: nginx-passenger }
  - { role: ruby }
  - { role: mysql }
  - { role: backups }
  - { role: redis }
  - { role: newrelic-sysmond }
  - role: newrelic.newrelic-infra
    nrinfragent_config:
      license_key: "{{ newrelic_license_key }}"
  - { role: mitmproxy }
  - { role: certbot }
  - role: geerlingguy.elasticsearch
    elasticsearch_version: 1.7.6
    elasticsearch_bind_host: 127.0.0.1
  - role: nickhammond.logrotate
    logrotate_scripts:
      - name: rails
        path: "/var/www/shared/log/*.log"
        options:
          - daily
          - rotate 7
          - compress
          - missingok
          - copytruncate
      - name: morph
        path: "/var/log/morph/*.log"
        options:
          - daily
          - rotate 7
          - compress
          - missingok
          - copytruncate
