---
# This playbook is for provisioning on a Linode box. It should be at least a Linode 24576 box and have
# 64 bit Ubuntu 16.04 LTS with 256 MB swap.
#
# To run in development:
# vagrant provision local
#
# To run in production:
# ansible-playbook --user=root -i provisioning/hosts provisioning/playbook.yml
#
# Run this from the root directory so that it picks up the ansible.cfg
# and so knows where to look for the ansible vault password

# Ubuntu 16.04 LTS doesn't come with python pre-installed. We need that for
# Ansible to work (for the gather facts). So install python first
- hosts: all
  become: true
  gather_facts: False

  tasks:
  - name: install python 2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

# Some features in the playbook need ansible2.5, so let's check for that first


- hosts: all
  pre_tasks:
    - name: Verify Ansible meets version requirements.
      assert:
        that: "ansible_version.full | version_compare('2.5', '>=')"
        msg: >
          "You must update Ansible to at least 2.5 to use this playbook."

- hosts: all
  become: true
  pre_tasks:
    - name: Upgrade all packages first
      apt:
        update_cache: yes
        cache_valid_time: 300
        upgrade: yes
  roles:
    - morph-app
    - discourse
  # The default behaviour is for handlers not to get called if a playbook fails
  # for any reason. Make handlers get called
  force_handlers: True
